# Generated by Django 2.0.13 on 2020-06-23 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0002_donateur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('description', models.CharField(max_length=40)),
                ('stock_groupe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blood_bank_app.Sang')),
            ],
        ),
    ]
