# Generated by Django 2.0.13 on 2020-06-23 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0004_auto_20200623_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donateur',
            old_name='Tel',
            new_name='tel',
        ),
    ]
